"""Four-field paper briefs. Legacy analyses keep their existing schema."""

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, StringConstraints, model_validator


# Stored by the program alongside the analysis; not generated by the model.
SCHEMA_VERSION = "lvr-brief-v1"

Text = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1)]
Category = Literal["MAIN", "METHOD", "EXPLORATORY", "PENDING", "EXCLUDE"]
Priority = Literal["P0", "P1", "P2", "NONE"]


class BriefAnalysis(BaseModel):
    """Only the paper's brief judgment; metadata and processing state are external."""

    model_config = ConfigDict(extra="forbid")

    category: Category = Field(description="论文的研究相关性类别")
    priority: Priority | None = Field(
        description="阅读顺序：入选为 P0/P1/P2，PENDING 为 null，EXCLUDE 为 NONE"
    )
    brief_summary: Text | None = Field(
        description="一句话概括论文研究什么、主要做什么；PENDING 或 EXCLUDE 可为 null"
    )
    relevance_reason: Text = Field(
        description="一句话说明具体联系、待核查线索或排除原因；潜在借鉴用推测措辞"
    )

    @model_validator(mode="after")
    def check_category_rules(self):
        if self.category in ("MAIN", "METHOD", "EXPLORATORY"):
            if self.priority not in ("P0", "P1", "P2"):
                raise ValueError("MAIN/METHOD/EXPLORATORY require priority P0/P1/P2")
            if self.brief_summary is None:
                raise ValueError("MAIN/METHOD/EXPLORATORY require brief_summary")
        elif self.category == "PENDING":
            if self.priority is not None:
                raise ValueError("PENDING requires priority=null")
        elif self.priority != "NONE":
            raise ValueError("EXCLUDE requires priority=NONE")
        return self
